registry:
  image: registry:2.6.1
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    REGISTRY_STORAGE_DELETE_ENABLED: "true"
  volumes:
    - ./data:/data
